### ISSUE TITLE
Continually tries to download "Download All" bulk zip file

### ISSUE THREAD

**Issue by firehawk12** [HuiiBuh/InstagramDownloader#130] opened 2021-01-10 08:38 UTC
**Describe the bug**
On Chrome, after generating the zip file and downloading the file, the extension continues to prompt the user to download the same zip file over and over again via the "Save As" prompt.  It's not clear how this can stop - sometimes closing the Instagram window will help, but sometimes it will continue to appear.

**To Reproduce**
1. Click Download All and wait for it to complete scanning and generating the file.
2. Chrome opens Save As prompt.
3. Save file
4. Chrome opens another Save As prompt.

**Expected behaviour**
The Save As Prompt to only appear once.

**Desktop (please complete the following information):**
 - Browser Chrome 
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by HuiiBuh** [comment] 2021-01-10 08:43
That does not sound good.
What will stop the prompt is closing the browser.
What is the resolution of your display? 
I will have a look at your problem.

**Comment by PublicConstructor** [comment] 2021-01-10 17:17
I can replicate this in Desktop Firefox 84.0.2 (64-bit). The save zip prompt came up about 4 times, each of which downloads the file though.

**Comment by PublicConstructor** [comment] 2021-01-10 17:30
The issue is that: 
https://github.com/HuiiBuh/InstagramDownloader/blob/b4686dee500fb7c22dd41b5970b0eec073db1964/src/ts/background/background.ts#L84-L89

Here the `let isFirst` is defined in local scope, so in each subsequent invocation of `downloadZIP`, `isFirst` is always `true` rather than the intended flipping to `false`. 

However rather than fixing this flag (which might be tricky in itself since this background script is constantly running the same instance I believe so somehow at some point it needs to be reset to true) it baffles me why `downloadZIP` is called multiple times in the first place. Indeed when I set a break point in `downloadBulk` it seems to be only called once but somehow `downloadZIP` just keep running...
https://github.com/HuiiBuh/InstagramDownloader/blob/b4686dee500fb7c22dd41b5970b0eec073db1964/src/ts/background/background.ts#L62-L64

**Comment by HuiiBuh** [comment] 2021-01-10 17:48
@PublicConstructor Thanks for your investigation! I don't think that the scope of isFist is the problem. isFist should only affect the percentage of the message which is sent to the frontend and not the download which happens in line 93-99.
And isFirst is supposed to be true for every time the download (downloadZip) is invoked. Without debugging this looks for me like downloadZip is called multiple times, which should not happen.

However I have not debugged anything, so you might also be right.

**Comment by HuiiBuh** [comment] 2021-01-10 17:50
Can you tell me how many posts you tried to download? Perhaps that might help debugging or does this bug happen every time you try to download multiple posts?

**Comment by PublicConstructor** [comment] 2021-01-10 18:32
> 
> 
> @PublicConstructor Thanks for your investigation! I don't think that the scope of isFist is the problem. isFist should only affect the percentage of the message which is sent to the frontend and not the download which happens in line 93-99.
> And isFirst is supposed to be true for every time the download (downloadZip) is invoked. Without debugging this looks for me like downloadZip is called multiple times, which should not happen.
> 
> However I have not debugged anything, so you might also be right.

I believe you are correct... Well then that leaves less clue from me.

**Comment by PublicConstructor** [comment] 2021-01-10 18:46
> 
> 
> Can you tell me how many posts you tried to download? Perhaps that might help debugging or does this bug happen every time you try to download multiple posts?

Try `https://www.instagram.com/world_record_egg/` - for me two ZIP download dialogs popped up simultaneously.

**Comment by firehawk12** [comment] 2021-01-11 15:06
Hi, not sure if this will help since you've already gotten into the code but for me I'm on 1920x1080 and I can't figure out how to shut down the save dialog - sometimes closing the Instagram window will work, but other times it will continue to download.

**Comment by HuiiBuh** [comment] 2021-01-11 16:24
@firehawk12 Thanks for the resolution. 
I will try to fix the bug tomorrow. As I said. Closing the whole browser should stop the dialog

**Closed** 2021-01-16 09:22 UTC
Labels: bug
