### ISSUE TITLE
When saving items it only saves random numbers. and not the usernames

### ISSUE THREAD

**Issue by ghost** [HuiiBuh/InstagramDownloader#184] opened 2021-05-06 13:47 UTC
When saving items it only saves random numbers. and not the usernames

**Comment by AlanTheBlank** [comment] 2021-05-06 14:42
What platform and can you describe your steps?

**Comment by legendado-2000** [comment] 2021-05-06 17:57
if you download from feed, story, profile. all get numbers in file download. im on the latest version of Google Chrome. Windows 10.

**Comment by legendado-2000** [comment] 2021-05-06 18:05
add to this:  4 other instagram downloader plugins also was affected by this. so most likely it was instagram that changed something. permissions or code

**Comment by AlanTheBlank** [comment] 2021-05-06 18:08
I'm having issues replicating the bug.  Have you tried downloading with just this instagram downloader extension as it sounds like you have multiple, which is the one available [here](https://chrome.google.com/webstore/detail/instagram-downloader/cpgaheeihidjmolbakklolchdplenjai)

**Comment by Fullmetalchemist** [comment] 2021-05-07 12:22
same with me, not just your plugin two more too stopped working properly on Firefox, Instagram has definitely changed something recently. Although I'm able to download fine with chrome.

**Comment by vemelon** [comment] 2021-05-08 11:34
I can confirm this. On 04.05.2021 (ddmmyyyy) was the last time it worked fine.

**Comment by AlanTheBlank** [comment] 2021-05-08 19:50
> 
> 
> same with me, not just your plugin two more too stopped working properly on Firefox, Instagram has definitely changed something recently. Although I'm able to download fine with chrome.

There's a pull request pending (#183) that fixes the firefox issue and is not related to this issue but rather #180 and #179

**Comment by Northtrop** [comment] 2021-05-27 22:05
I also have the same issue, using Chromium. Oddly enough, it appears on one Chromium profile and not the other.
I've also noticed the same issue as #196, as well as my account getting frequently locked out.
It definetly seems like Instagram is cracking down on such non-standard use.

**Comment by katsos** [comment] 2021-06-03 01:01
I found the problem https://github.com/HuiiBuh/InstagramDownloader/blame/c36c8ef6e4b1aae393e7773dadb635f3c42bc7a5/src/ts/background/download.ts#L35

Seems like arguments at this point come right but `browser.downloads.download` doens't take in account `filename` option.

I couldn't find a change that may broke this chunk as long as this code goes back to  Mar 24, 2020
https://github.com/HuiiBuh/InstagramDownloader/commit/07e6df9252beab4a0af7f7475a40c44792ed75f4#diff-34dd6ba5eb24c36bbaf3b83fd21fe816d26df329a639ecb1e47c46789d50193fR16

There might be something wrong with the `browser` library. I didn't have to time to investigate further.
Hope it helped. If you cannot progress this one, ping me and I will come back with the solution.

**Comment by firebirdsonic** [comment] 2021-06-04 20:10
> I found the problem https://github.com/HuiiBuh/InstagramDownloader/blame/c36c8ef6e4b1aae393e7773dadb635f3c42bc7a5/src/ts/background/download.ts#L35
> 
> Seems like arguments at this point come right but `browser.downloads.download` doens't take in account `filename` option.
> 
> I couldn't find a change that may broke this chunk as long as this code goes back to Mar 24, 2020
> [07e6df9#diff-34dd6ba5eb24c36bbaf3b83fd21fe816d26df329a639ecb1e47c46789d50193fR16](https://github.com/HuiiBuh/InstagramDownloader/commit/07e6df9252beab4a0af7f7475a40c44792ed75f4#diff-34dd6ba5eb24c36bbaf3b83fd21fe816d26df329a639ecb1e47c46789d50193fR16)
> 
> There might be something wrong with the `browser` library. I didn't have to time to investigate further.
> Hope it helped. If you cannot progress this one, ping me and I will come back with the solution.

It does take `filename` into account https://github.com/Lusito/webextension-polyfill-ts/blob/8f83cd05ad8b613680c673d64927a250436b00e2/lib/downloads.d.ts#L335

**Comment by katsos** [comment] 2021-06-04 22:18
> It does take `filename` into account https://github.com/Lusito/webextension-polyfill-ts/blob/8f83cd05ad8b613680c673d64927a250436b00e2/lib/downloads.d.ts#L335

This is what is written in the source code. Doesn't mean it works.

**Comment by firebirdsonic** [comment] 2021-06-05 10:34
> > It does take `filename` into account https://github.com/Lusito/webextension-polyfill-ts/blob/8f83cd05ad8b613680c673d64927a250436b00e2/lib/downloads.d.ts#L335
> 
> This is what is written in the source code. Doesn't mean it works properly.

Oh yeah, 100%. I'm just trying to say the problem may be elsewhere.

**Comment by weiweihuanghuang** [comment] 2021-06-25 03:58
I have the same issue that filenames are as the original files instead of username etc

**Comment by vemelon** [comment] 2021-06-25 09:57
Yeah when is this going to get fixed? It's really annoying :(

**Comment by katsos** [comment] 2021-06-25 10:34
Hello guys, could you please post a list of your browser extensions?
I found out that for me it was an extension that was creating the problem.

For me it was this one https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

**Comment by vemelon** [comment] 2021-06-25 12:35
> Hello guys, could you please post a list of your browser extensions?
> I found out that for me it was an extension that was creating the problem.
> 
> For me it was this one https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

oh my god thank you!!! I had image downloader as well, deactivating it fixed the problem :) weird, how can they cross each other...

**Comment by firebirdsonic** [comment] 2021-06-28 11:52
> Hello guys, could you please post a list of your browser extensions?
> I found out that for me it was an extension that was creating the problem.
> 
> For me it was this one https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

Solved for me too! Thanks!

**Comment by HuiiBuh** [comment] 2021-06-30 11:56
Hi, as the problem seems to be fixed I will close the issue

**Closed by HuiiBuh** 2021-06-30 11:56 UTC
Labels: bug
