### ISSUE TITLE
Download All not working on latest firefox 

### ISSUE THREAD

**Issue by fiascokid** [HuiiBuh/InstagramDownloader#95] opened 2020-07-21 17:31 UTC
It often gets stuck on "please wait until download continues..." 
My internet is fine and I even left it to download while streaming some shows. 
Sometimes it takes a few seconds, sometimes a few minutes, most of the time it doesn't work at all.  
Also, if the download completes there's always some pictures missing. 

Firefox version 78.0.2 (64-bit)
Other add-ons I have currently installed:
ublock origin
duckduckgo
privacy badger
reddit enhancement
facebook container

**Comment by HuiiBuh** [comment] 2020-07-21 21:29
Are there some accounts (for example accounts with a lot of videos) which are especially bad to download?

**Comment by fiascokid** [comment] 2020-07-22 13:56
I tried it on an account without videos and it always work, and another one with only one video also worked but there were some pictures still missing. I noticed most of the time the download is around 50+ images.

**Comment by HuiiBuh** [comment] 2020-07-22 19:22
Thanks that helps a lot

**Comment by HuiiBuh** [comment] 2020-07-29 16:30
Hey I just uploaded Version 3.2.2.
Could you please tell me if download all is working now?

**Comment by Marisa-desu** [comment] 2020-07-29 18:17
Just tested it, still hangs at the "please wait until download continues..." screen.

**Comment by HuiiBuh** [comment] 2020-07-29 19:06
@Marisa-desu there should be now a counter which shows you the progress. 

Where exactly does it get stuck?

**Comment by Marisa-desu** [comment] 2020-07-29 19:10
@HuiiBuh Well, at 100%, I guess? Like I said, it hangs at the "please wait until download continues..." thing and never actually saves the zipped images. I can try with some other insta accounts, see if only certain ones don't work.

**Comment by Marisa-desu** [comment] 2020-07-29 19:15
@HuiiBuh Ok, I tested it with a smaller account and this time it actually worked.

**Comment by HuiiBuh** [comment] 2020-07-29 19:37
@Marisa-desu I think in this case you have not the newest version of the addon (3.2.2) installed. 
Otherwise you would know how many image have been collected (see image)

![image](https://user-images.githubusercontent.com/46561026/88844843-953ff700-d1e3-11ea-8240-693f2732ee42.png)

**Comment by Marisa-desu** [comment] 2020-07-29 19:42
But I do and I am trying to download a profile with about 180 pics right now and it shows me this for at least 30 minutes or so and I'm getting lots of "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/logging_client_events. (Reason: CORS request did not succeed)." errors in the console.
![2020-07-29 21_39_32-муж ники (@emquizii) • Instagram photos and videos](https://user-images.githubusercontent.com/47089596/88845267-329b2b00-d1e4-11ea-99a8-0e65f8e96745.jpg)

**Comment by HuiiBuh** [comment] 2020-07-29 19:48
OK, in this case not a single request is successful, which is strange.  
Have you tried to set your tracking protection in privacy and security to standard?

**Comment by Marisa-desu** [comment] 2020-07-29 19:51
It is on standard but I guess ublock origin could be the problem then. Will try without.

**Comment by Marisa-desu** [comment] 2020-07-29 19:55
No more errors in the console, for now. Still doesn't show me any progress.

**Comment by HuiiBuh** [comment] 2020-07-29 19:58
Should not be the problem. 
I have got ublock enabled. 
Do you have the facebook container, or any other addons installed?

**Comment by Marisa-desu** [comment] 2020-07-29 20:04
Besides ublock I have no other security or ad block related addons. Only other thing that could mess things up are scripts I use with Tampermonkey but the only script active on insta is linkify++, which makes plain text links clickable.
Here are all the addons I have installed, just in case: BetterTTV, FrankerFaceZ, Pixiv Toolkit, Reddit Enhancement Suite, Stylus, Translate web pages, Twitter Media Downloader.

**Comment by HuiiBuh** [comment] 2020-07-29 20:04
I just downloaded the first 100 image (180mb) of https://www.instagram.com/adam.ondra/. 
I had to interrupt the image collection with the button because the collection stopped at 99 of 100, but apart from that it worked. 

Perhaps you could tell me your screen resolution

**Comment by Marisa-desu** [comment] 2020-07-29 20:06
2560x1080 but I don't have ff maximized, almost no webpage uses that much horizontal space.

**Comment by Marisa-desu** [comment] 2020-07-29 20:08
Clicking "Stop collecting images and start downloading" does nothing for me btw.

**Comment by HuiiBuh** [comment] 2020-07-29 20:17
Thanks a lot for the help. Could just now reproduce the issue. 

I will fix it soon

**Comment by HuiiBuh** [comment] 2020-07-29 21:45
Should be fixed in v3.2.3

**Comment by Marisa-desu** [comment] 2020-07-29 23:14
Woks now, thx. 👍

**Closed** 2020-07-30 13:22 UTC
Labels: bug
