### ISSUE TITLE
Download button disappears on homepage

### ISSUE THREAD

**Issue by f0rr357** [HuiiBuh/InstagramDownloader#80] opened 2020-03-21 16:40 UTC
Hello, i'm on firefox 74.0 Windows 10 64 bit (10.0.18362) and when i open instagram.com i see the download button only on the first post, i restarted firefox refreshed the page but nothing changes. My version of the extension is 2.3.2 maybe something with the update? Also download button works flawlessy in specific page (multiple posts and single one) Thank you in advance
![Screenshot_2020-03-21 Instagram](https://user-images.githubusercontent.com/54697277/77231799-7b3f3980-6b9d-11ea-9bb7-fd2cfc070c59.jpg)

**Comment by HuiiBuh** [comment] 2020-03-21 17:24
Hi thanks for the Report.
Instagram is changing a lot in the last days. I will make some major changes the next weak amd make improvements.

**Comment by superfreeman1989** [comment] 2020-03-25 18:00
New posts that loaded when you scroll down have download button missing. If you click "go to post" then go back to home page, the download button appears again.

**Comment by HuiiBuh** [comment] 2020-03-25 18:12
Interesting.
I am currentely developing Version 3 which will fix all issues

**Comment by HuiiBuh** [comment] 2020-03-29 12:59
Hey please check out the newest Version. Everything should be fixed

**Closed** 2020-03-30 09:59 UTC
Labels: bug

**Comment by superfreeman1989** [comment] 2020-04-01 01:07
Working now. Thanks!

**Comment by HuiiBuh** [comment] 2020-04-09 15:23
Hey could one of you please verify that the bulk download is working. 
I got some complaints but could not reproduce the issue.
